
language: node_js
node_js:
  - 8
  - 10
  - 12
  - 14
cache:
  directories:
    - node_modules
before_script:
  - echo 1
script:
  - npm run lint
  - npm run test-cov
  - npm run bench
after_script:
  # only upload the coverage.json file
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json